#!/usr/bin/env bash
#
# Run all dotfiles handlers

set -e

pushd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
